### ISSUE TITLE
Wordpress 5.4 compatibility issue

### ISSUE THREAD

**Issue by wallenium** [daggerhart/wp-custom-menu-items#1]
once I use the custom_menu_items::add_item(), the menu is gone... not sure what happens...

**Comment by wallenium** [comment]
nav-menu-template.php, line 217 is causing the problems, Not sure why. 

`$sorted_menu_items = apply_filters( 'wp_nav_menu_objects', $sorted_menu_items, $args );`

**Comment by RichardCoffee** [comment]
Are you using any menu plugins?  Check the input and output of the `wp_get_nav_menu_object` method, lines 68-73.  If these are good, then the problem is somewhere else.

I use this and didn't have any problems with the 5.4 upgrade.

**Comment by wallenium** [comment]
Hi Richard,
thanks a lot for your input.
As said, the wp_nav_menu_objects seems to be the problem.
Once I commented out nav-menu-template.php, line 217, the problem is gone.

I will now check my plugins, this is a good hint. Could be multilingual press - this is causing troubles some times, and was updated a minute prior to wordpress...

**Comment by daggerhart** [comment]
@wallenium Thanks for the report. I'm looking at `nav-menu-template.php` linke `217`, and it says this filter has been here since 3.1.0, so it's not the filter itself that is a new problem. I searched WP 5.4 for `wp_nav_menu_objects` to see if there were any new hooks added in 5.4, but did not find any.

It looks like 5.4 did have new menu code added (https://make.wordpress.org/core/2020/02/25/wordpress-5-4-introduces-new-hooks-to-add-custom-fields-to-menu-items/), but at a glance I don't see how this would have caused a problem with the `wp_nav_menu_objects` filter.

Could you provide an example of your code that uses this `custom_menu_items` class? That might help figure out the problem.

Also, do you have any other plugins installed that may attempt to modify the menu or menu items?

**Comment by wallenium** [comment]
@daggerhart 
I nailed it down to multilingual press.
add_filter('wp_nav_menu_objects', wpHookProxy([$itemFilter, 'filterItems']), PHP_INT_MAX);

this seems to cause the issues. I will forward it to the multilingual press guys.

**Comment by daggerhart** [comment]
Thanks for look into that and letting us know what the problem was. It should help if other people experience this.
